import type { DetectionReport, Evidence, Finding, HarnessMatch, TemplateId } from './detect.js';

export const TEMPLATE_IDS: TemplateId[] = ['sdk-workstream', 'queue', 'mcp'];

export interface TemplateInput {
  harnessName: string;
  apiUrl: string;
  credentialEnv: string;
  template: TemplateId;
  report: DetectionReport;
  match: HarnessMatch | null;
}

export function className(harnessName: string): string {
  const pascal = harnessName
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('');
  return `${/^[0-9]/.test(pascal) ? `H${pascal}` : pascal || 'Host'}Harness`;
}

export function renderAdapter(input: TemplateInput): string {
  switch (input.template) {
    case 'sdk-workstream':
      return sdkWorkstream(input);
    case 'queue':
      return queue(input);
    case 'mcp':
      return mcpOnly(input);
  }
}

export function renderHarnessConfig(
  input: TemplateInput & { workspaceId: string; adapterPath: string },
): string {
  const { report, match } = input;
  const names = (findings: Finding[]) => findings.map((f) => f.name);
  const config = {
    version: 1,
    harness: input.harnessName,
    template: input.template,
    apiUrl: input.apiUrl,
    workspaceId: input.workspaceId,
    credentialEnv: input.credentialEnv,
    adapter: input.adapterPath,
    agents: { '<celune-agent-id>': '<harness-agent-id>' },
    detected: {
      shape: match?.shape ?? null,
      confidence: match?.confidence ?? 0,
      runPrimitive: match?.runPrimitive ? describe(match.runPrimitive) : null,
      schedulePrimitive: match?.schedulePrimitive ? describe(match.schedulePrimitive) : null,
      persistence: names(report.persistence),
      webFramework: names(report.webFramework),
      auth: names(report.auth),
    },
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

export function renderEnvExample(input: TemplateInput & { workspaceId: string }): string {
  return [
    '# Celune harness connection. Copy these into the server environment or secret manager.',
    `CELUNE_API_URL=${input.apiUrl}`,
    `CELUNE_WORKSPACE_ID=${input.workspaceId}`,
    '# API key with write scope. The adapter uses it to report run events. Never commit the value.',
    `${input.credentialEnv}=`,
    '# Optional: HS256 secret shared with Celune (CELUNE_HOST_JWT_SECRET) for minting agent tokens.',
    'CELUNE_HOST_JWT_SECRET=',
    '',
  ].join('\n');
}

function describe(finding: Finding): { name: string; files: string[] } {
  return { name: finding.name, files: finding.evidence.map(ref) };
}

function ref(e: Evidence): string {
  return e.line ? `${e.file}:${e.line}` : e.file;
}

function header(input: TemplateInput, summary: string[]): string {
  const { match } = input;
  const lines = [
    `Celune harness adapter for "${input.harnessName}", generated by \`npx @celuneai/cli connect\`.`,
    '',
    ...summary,
    '',
  ];
  if (match?.runPrimitive) {
    lines.push(`Detected run primitive: ${match.runPrimitive.name}`);
    for (const e of match.runPrimitive.evidence.slice(0, 3)) lines.push(`  ${ref(e)} (${e.note})`);
  }
  if (match?.schedulePrimitive) {
    lines.push(`Detected schedule primitive: ${match.schedulePrimitive.name}`);
    for (const e of match.schedulePrimitive.evidence.slice(0, 3))
      lines.push(`  ${ref(e)} (${e.note})`);
  }
  lines.push(
    '',
    'Next steps: fill in the TODOs, register the adapter with HarnessRegistry, map agents in',
    '.celune/harness.json, and call reportRunEvent wherever a run changes state. Then run',
    '`npx @celuneai/cli connect --check`.',
  );
  const safe = lines.map((l) =>
    l.replace(/[\u0000-\u001f\u007f\u2028\u2029]+/g, ' ').replace(/\*\//g, '*\\/'),
  );
  return `/**\n${safe.map((l) => (l ? ` * ${l}` : ' *')).join('\n')}\n */`;
}

function reporter(input: TemplateInput): string {
  return `export interface RunEventReport {
  /** Stable per transition, for example \`\${runId}:finalize\`, so retries are deduplicated. */
  eventId: string;
  taskId: string;
  runId: string;
  status: HarnessRunStatus;
  occurredAt?: string;
  outcome?: string | null;
  error?: string | null;
  progress?: Record<string, unknown>;
}

/** Posts a run state change to Celune. Call it where the host writes run status. */
export async function reportRunEvent(
  event: RunEventReport,
  env: Record<string, string | undefined> = process.env,
): Promise<void> {
  const apiUrl = (env.CELUNE_API_URL ?? '${input.apiUrl}').replace(/\\/+$/, '');
  const credential = env.${input.credentialEnv};
  if (!credential) throw new Error('${input.credentialEnv} is not set');
  const response = await fetch(\`\${apiUrl}/v1/harness/events\`, {
    method: 'POST',
    headers: { authorization: \`Bearer \${credential}\`, 'content-type': 'application/json' },
    body: JSON.stringify({
      event_id: event.eventId,
      task_id: event.taskId,
      harness: HARNESS_NAME,
      run_id: event.runId,
      status: event.status,
      occurred_at: event.occurredAt ?? new Date().toISOString(),
      outcome: event.outcome ?? null,
      error: event.error ?? null,
      ...(event.progress ? { progress: event.progress } : {}),
    }),
  });
  if (!response.ok) {
    throw new Error(\`Celune rejected event \${event.eventId}: \${response.status}\`);
  }
}

/** TODO: map every host run status onto Celune's eight run statuses. */
export function toRunStatus(hostStatus: string): HarnessRunStatus {
  switch (hostStatus.toLowerCase()) {
    case 'queued':
    case 'pending':
    case 'waiting_for_capacity':
      return 'queued';
    case 'running':
    case 'active':
    case 'dispatched':
      return 'running';
    case 'waiting':
    case 'parked':
    case 'awaiting_input':
      return 'waiting';
    case 'completed':
    case 'succeeded':
    case 'success':
      return 'succeeded';
    case 'cancelled':
    case 'canceled':
      return 'cancelled';
    case 'budget_exceeded':
      return 'budget_exceeded';
    case 'timed_out':
    case 'timeout':
      return 'timed_out';
    default:
      return 'failed';
  }
}

/** The brief the agent receives. It names the Celune MCP tools the run may use. */
export function briefFor(task: HarnessTaskInput, context: HarnessRunContext): string {
  return [
    \`Celune task \${task.id} (priority \${task.priority}): \${task.title}\`,
    '',
    task.description?.trim() || 'No description.',
    '',
    \`You are the Celune agent "\${context.agentId}". Read the task with get_task and post progress with add_comment.\`,
    'Create follow-up work with create_task. Do not call complete_task or block_task on this task:',
    'the run result reports its status to Celune. End with a short summary; it becomes the task outcome.',
  ].join('\\n');
}`;
}

const CORE_IMPORTS = `import {
  defaultRunEventMapping,
  type HarnessAdapter,
  type HarnessCapabilities,
  type HarnessEffect,
  type HarnessHeartbeat,
  type HarnessRunContext,
  type HarnessRunEvent,
  type HarnessRunRef,
  type HarnessRunStatus,
  type HarnessTaskInput,
  type StartRunResult,
} from '@celuneai/core';`;

function sdkWorkstream(input: TemplateInput): string {
  const name = className(input.harnessName);
  return `${header(input, [
    'Shape: a Claude Agent SDK host where a run lives inside a container of work',
    '(for example a Workstream holding AgentRuns, dispatched by a durable queue).',
    'Modeled on @celuneai/harness-headways. Implement HostRuntime with your own run service.',
  ])}
${CORE_IMPORTS}

export const HARNESS_NAME = '${input.harnessName}';

/** How one harness agent runs in this host. Keyed by the harness agent id in the agent map. */
export interface RunProfile {
  model: string;
  /** Spend ceiling for one run, when the host enforces budgets. */
  budgetUsdMax?: number;
}

/** The host calls the adapter needs. TODO: implement these against the run service. */
export interface HostRuntime {
  /** Creates the container for a task's work (for example a Workstream). */
  createContainer(input: { goal: string; clientRequestId: string }): Promise<{ id: string }>;
  /** Starts one agent run in the container with the brief as its first message. */
  createRun(input: {
    containerId: string;
    brief: string;
    profile: RunProfile;
    clientRequestId: string;
  }): Promise<{ id: string; status: string }>;
  getRun(runId: string): Promise<{ status: string; costUsd?: number } | null>;
  cancelRun(runId: string): Promise<void>;
}

export interface ${name}Options {
  runtime: HostRuntime;
  profiles: Record<string, RunProfile>;
  /** Web origin, for the run link written to the task. */
  webUrl?: string;
  /** Path of a container page under webUrl. */
  containerPath?: (containerId: string) => string;
  clock?: () => Date;
}

export class ${name} implements HarnessAdapter {
  private readonly options: ${name}Options;
  private readonly containers = new Map<string, string>();
  private readonly clock: () => Date;

  constructor(options: ${name}Options) {
    this.options = options;
    this.clock = options.clock ?? (() => new Date());
  }

  capabilities(): HarnessCapabilities {
    return { name: HARNESS_NAME, version: '0.1.0', cancel: true, heartbeat: true, budgets: true };
  }

  async startRun(task: HarnessTaskInput, context: HarnessRunContext): Promise<StartRunResult> {
    const profile = this.options.profiles[context.harnessAgentId];
    if (!profile) throw new Error(\`No run profile for harness agent \${context.harnessAgentId}\`);
    const attempt = this.clock().getTime().toString(36);

    let containerId = this.containers.get(task.id);
    if (!containerId) {
      const goal = task.description?.trim() ? \`\${task.title}\\n\\n\${task.description.trim()}\` : task.title;
      const container = await this.options.runtime.createContainer({
        goal: goal.slice(0, 4_000),
        clientRequestId: \`celune:\${task.id}:container\`,
      });
      containerId = container.id;
      this.containers.set(task.id, containerId);
    }

    const run = await this.options.runtime.createRun({
      containerId,
      brief: briefFor(task, context),
      profile,
      clientRequestId: \`celune:\${task.id}:run:\${attempt}\`,
    });
    const web = this.options.webUrl?.replace(/\\/$/, '');
    const path = this.options.containerPath?.(containerId) ?? \`/\${containerId}\`;
    return { runId: run.id, status: toRunStatus(run.status), url: web ? \`\${web}\${path}\` : null };
  }

  onRunEvent(event: HarnessRunEvent): HarnessEffect {
    return defaultRunEventMapping(event);
  }

  async heartbeat(runRef: HarnessRunRef): Promise<HarnessHeartbeat> {
    const run = await this.options.runtime.getRun(runRef.runId);
    const at = this.clock().toISOString();
    if (!run) return { status: 'queued', at };
    return { status: toRunStatus(run.status), at, progress: { cost_usd: run.costUsd } };
  }

  async cancelRun(runRef: HarnessRunRef): Promise<void> {
    await this.options.runtime.cancelRun(runRef.runId);
  }
}

${reporter(input)}
`;
}

function queue(input: TemplateInput): string {
  const name = className(input.harnessName);
  return `${header(input, [
    'Shape: a job queue or HTTP task runner. A claim enqueues one job per run; the',
    'worker reports its lifecycle to Celune with reportRunEvent.',
    ...wiringHint(input.match),
  ])}
${CORE_IMPORTS}

export const HARNESS_NAME = '${input.harnessName}';

/** The job payload a claim enqueues. */
export interface CeluneJob {
  taskId: string;
  title: string;
  description: string | null;
  priority: string;
  projectId: string | null;
  workspaceId: string;
  agentId: string;
  harnessAgentId: string;
  brief: string;
}

export interface ${name}Options {
  /** TODO: add the job to your queue and return its id. Use jobId for deduplication when the queue supports it. */
  enqueue(job: CeluneJob, jobId: string): Promise<{ id: string }>;
  /** Optional: read a job's state for heartbeats. */
  getJob?(jobId: string): Promise<{ status: string } | null>;
  /** Optional: stop a job. */
  cancelJob?(jobId: string): Promise<void>;
  clock?: () => Date;
}

export class ${name} implements HarnessAdapter {
  private readonly options: ${name}Options;
  private readonly clock: () => Date;

  constructor(options: ${name}Options) {
    this.options = options;
    this.clock = options.clock ?? (() => new Date());
  }

  capabilities(): HarnessCapabilities {
    return {
      name: HARNESS_NAME,
      version: '0.1.0',
      cancel: Boolean(this.options.cancelJob),
      heartbeat: Boolean(this.options.getJob),
      budgets: false,
    };
  }

  async startRun(task: HarnessTaskInput, context: HarnessRunContext): Promise<StartRunResult> {
    const jobId = \`celune-\${task.id}-\${this.clock().getTime().toString(36)}\`;
    const job = await this.options.enqueue(
      {
        taskId: task.id,
        title: task.title,
        description: task.description,
        priority: task.priority,
        projectId: task.projectId,
        workspaceId: task.workspaceId,
        agentId: context.agentId,
        harnessAgentId: context.harnessAgentId,
        brief: briefFor(task, context),
      },
      jobId,
    );
    return { runId: job.id, status: 'queued' };
  }

  onRunEvent(event: HarnessRunEvent): HarnessEffect {
    return defaultRunEventMapping(event);
  }

  async heartbeat(runRef: HarnessRunRef): Promise<HarnessHeartbeat> {
    const job = await this.options.getJob?.(runRef.runId);
    return { status: job ? toRunStatus(job.status) : 'queued', at: this.clock().toISOString() };
  }

  async cancelRun(runRef: HarnessRunRef): Promise<void> {
    await this.options.cancelJob?.(runRef.runId);
  }
}

${reporter(input)}
`;
}

function mcpOnly(input: TemplateInput): string {
  const name = className(input.harnessName);
  return `${header(input, [
    'Shape: MCP-only. Agents are coding sessions (Claude Code, Cursor) that reach Celune',
    'through its MCP tools. There is no run service to start, so startRun records a',
    'session and the agent claims and reports through the celune-task and celune-status',
    'skills. This adapter is optional: without one, claims still work and run events',
    'still apply with the default mapping.',
  ])}
${CORE_IMPORTS}

export const HARNESS_NAME = '${input.harnessName}';

export class ${name} implements HarnessAdapter {
  private readonly clock: () => Date;

  constructor(clock: () => Date = () => new Date()) {
    this.clock = clock;
  }

  capabilities(): HarnessCapabilities {
    return { name: HARNESS_NAME, version: '0.1.0', cancel: false, heartbeat: false, budgets: false };
  }

  async startRun(task: HarnessTaskInput, _context: HarnessRunContext): Promise<StartRunResult> {
    // TODO: notify the session owner (a chat message, an issue comment) if the host has a channel for it.
    return { runId: \`session:\${task.id}:\${this.clock().getTime().toString(36)}\`, status: 'queued' };
  }

  onRunEvent(event: HarnessRunEvent): HarnessEffect {
    return defaultRunEventMapping(event);
  }

  async heartbeat(_runRef: HarnessRunRef): Promise<HarnessHeartbeat> {
    return { status: 'queued', at: this.clock().toISOString() };
  }

  async cancelRun(_runRef: HarnessRunRef): Promise<void> {}
}

${reporter(input)}
`;
}

function wiringHint(match: HarnessMatch | null): string[] {
  const label = match?.label ?? '';
  if (label.includes('BullMQ')) {
    return [
      'BullMQ wiring: in the Worker processor call reportRunEvent with status running at',
      "start; on worker 'completed' send succeeded with the result as outcome; on 'failed'",
      'send failed (or timed_out) with the error. Use `${job.id}:<transition>` as eventId.',
    ];
  }
  if (label.includes('DBOS')) {
    return [
      'DBOS wiring: report from a DBOS step after each run write, so a retry resends the same',
      'eventId. Send running when the workflow starts and succeeded or failed when it ends.',
    ];
  }
  if (label.includes('Temporal')) {
    return [
      'Temporal wiring: report from an activity at workflow start and end. Temporal retries',
      'activities, so keep eventId stable per transition.',
    ];
  }
  if (label.includes('Inngest')) {
    return [
      'Inngest wiring: report inside step.run blocks at start and end of the function so',
      'retries reuse the step result.',
    ];
  }
  if (label.includes('pg-boss')) {
    return ['pg-boss wiring: report at the start and end of the work handler.'];
  }
  if (match?.shape === 'http-runner') {
    return [
      'HTTP wiring: enqueue calls your task endpoint; report running when the handler',
      'accepts the job and a terminal status when it finishes.',
    ];
  }
  return ['Report running when a job starts and a terminal status when it ends.'];
}
