#!/usr/bin/env bash
# generate-harness.sh — Generate a GOAL.md and test baseline for a skill.
# Creates GOAL.md from template if missing, runs test-runner, saves baseline.
# This file is LOCKED. Agents MUST NOT modify it.
#
# Usage: generate-harness.sh <skill-directory> [--force]
# --force: Overwrite existing GOAL.md and baseline

set -euo pipefail

SKILL_DIR="${1:?Usage: generate-harness.sh <skill-directory> [--force]}"
FORCE="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATES_DIR="$(dirname "$SCRIPT_DIR")/_templates"

SKILL_NAME="$(basename "$SKILL_DIR")"

# Verify skill directory
if [ ! -d "$SKILL_DIR" ]; then
  echo "Error: Skill directory not found: $SKILL_DIR" >&2
  exit 1
fi

# Find the skill file
SKILL_FILE=""
if [ -f "$SKILL_DIR/SKILL.md" ]; then
  SKILL_FILE="$SKILL_DIR/SKILL.md"
elif [ -f "$SKILL_DIR/CLAUDE.md" ]; then
  SKILL_FILE="$SKILL_DIR/CLAUDE.md"
else
  echo "Error: No SKILL.md or CLAUDE.md found in $SKILL_DIR" >&2
  exit 1
fi

echo "Generating harness for: $SKILL_NAME"

# ── 1. Create GOAL.md if missing ──
if [ ! -f "$SKILL_DIR/GOAL.md" ] || [ "$FORCE" = "--force" ]; then
  if [ -f "$TEMPLATES_DIR/GOAL.md" ]; then
    # Determine complexity for max_iterations and mode
    line_count=$(wc -l < "$SKILL_FILE" | tr -d ' ')
    h2_count=$(grep -c '^## ' "$SKILL_FILE" 2>/dev/null || echo "0")

    if [ "$line_count" -gt 200 ] || [ "$h2_count" -gt 10 ]; then
      complexity="high"
      max_iter=20
      time_cap=30
    elif [ "$line_count" -gt 50 ] || [ "$h2_count" -gt 4 ]; then
      complexity="medium"
      max_iter=15
      time_cap=20
    else
      complexity="low"
      max_iter=10
      time_cap=15
    fi

    # Generate a customized GOAL.md
    # Use quoted heredoc to prevent command injection, then substitute variables
    generated_date=$(date +%Y-%m-%d)
    cat > "$SKILL_DIR/GOAL.md" << 'GOALEOF'
---
metric: composite
direction: higher_is_better
mode: continuous
max_iterations: __MAX_ITER__
staleness_threshold_days: 14
time_cap_minutes: __TIME_CAP__

constraints:
  - "Never remove or rename existing sections"
  - "Never modify GOAL.md or files in tests/"
  - "Preserve the skill's argument format and trigger conditions"
  - "Never add more than 50 lines in a single iteration"

action_catalog:
  - priority: P0
    category: coverage
    description: "Add missing edge case handling for common failure modes"
    impact: high

  - priority: P1
    category: clarity
    description: "Replace vague instructions with concrete file paths and commands"
    impact: high

  - priority: P1
    category: approach
    description: "Ensure every approach step is actionable (verb + noun + target)"
    impact: medium

  - priority: P2
    category: structure
    description: "Verify all required sections present and correctly ordered"
    impact: medium

  - priority: P2
    category: coverage
    description: "Add error recovery steps for each approach step that can fail"
    impact: medium

  - priority: P3
    category: clarity
    description: "Add concrete examples for complex or ambiguous instructions"
    impact: low
---

# /__SKILL_NAME__ — Fitness Function

Complexity: __COMPLEXITY__ (__LINE_COUNT__ lines, __H2_COUNT__ sections)
Auto-generated by generate-harness.sh on __DATE__.
GOALEOF
    # Substitute placeholders with actual values (safe — no command execution)
    sed -i '' \
      -e "s/__MAX_ITER__/${max_iter}/" \
      -e "s/__TIME_CAP__/${time_cap}/" \
      -e "s/__SKILL_NAME__/${SKILL_NAME}/" \
      -e "s/__COMPLEXITY__/${complexity}/" \
      -e "s/__LINE_COUNT__/${line_count}/" \
      -e "s/__H2_COUNT__/${h2_count}/" \
      -e "s/__DATE__/${generated_date}/" \
      "$SKILL_DIR/GOAL.md"
    echo "  Created GOAL.md (complexity: $complexity, max_iterations: $max_iter)"
  else
    echo "  Warning: Template not found at $TEMPLATES_DIR/GOAL.md, skipping GOAL.md creation" >&2
  fi
else
  echo "  GOAL.md already exists (use --force to overwrite)"
fi

# ── 2. Create tests/ directory ──
mkdir -p "$SKILL_DIR/tests"

# ── 3. Run test-runner and save baseline ──
if [ ! -f "$SKILL_DIR/tests/baseline.json" ] || [ "$FORCE" = "--force" ]; then
  echo "  Running test-runner for baseline..."
  if result=$("$SCRIPT_DIR/test-runner.sh" "$SKILL_DIR" 2>/dev/null); then
    echo "$result" > "$SKILL_DIR/tests/baseline.json"
    baseline_score=$(echo "$result" | python3 -c "import sys,json; print(json.load(sys.stdin).get('score', 0))" 2>/dev/null || echo "?")
    echo "  Baseline saved: score=$baseline_score"
  else
    echo '{"score": 0, "error": "Test runner failed during baseline generation"}' > "$SKILL_DIR/tests/baseline.json"
    echo "  Warning: Test runner failed, baseline set to 0" >&2
  fi
else
  echo "  Baseline already exists (use --force to overwrite)"
fi

# ── 4. Create empty improvements.jsonl if missing ──
if [ ! -f "$SKILL_DIR/improvements.jsonl" ]; then
  touch "$SKILL_DIR/improvements.jsonl"
  echo "  Created empty improvements.jsonl"
fi

echo "Done: $SKILL_NAME"
