#!/usr/bin/env bash
# session-state.sh — Manage SKILL_STATE.md for cross-session persistence.
# Reads/writes compressed improvement state for stateless agent resumption.
# This file is LOCKED. Agents MUST NOT modify it.
#
# Usage:
#   session-state.sh read <skill-directory>     — Output current state as JSON
#   session-state.sh write <skill-directory>     — Generate SKILL_STATE.md from improvements.jsonl
#   session-state.sh summary <skill-directory>   — One-line summary for context loading

set -euo pipefail

ACTION="${1:?Usage: session-state.sh <read|write|summary> <skill-directory>}"
SKILL_DIR="${2:?Usage: session-state.sh <read|write|summary> <skill-directory>}"
SKILL_NAME="$(basename "$SKILL_DIR")"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

case "$ACTION" in

read)
  # Output current state as JSON for agent context loading
  if [ ! -f "$SKILL_DIR/SKILL_STATE.md" ]; then
    echo '{"exists": false}'
    exit 0
  fi

  python3 -c "
import json, re

with open('$SKILL_DIR/SKILL_STATE.md') as f:
    content = f.read()

# Parse frontmatter
parts = content.split('---')
state = {'exists': True, 'raw': content}

if len(parts) >= 3:
    fm = parts[1]
    for line in fm.strip().split('\n'):
        if ':' in line:
            key, val = line.split(':', 1)
            state[key.strip()] = val.strip()

# Parse sections
sections = {}
current_section = None
for line in content.split('\n'):
    if line.startswith('## '):
        current_section = line[3:].strip()
        sections[current_section] = []
    elif current_section and line.strip():
        sections[current_section].append(line.strip())

state['sections'] = {k: '\n'.join(v) for k, v in sections.items()}
print(json.dumps(state, indent=2))
"
  ;;

write)
  # Generate SKILL_STATE.md from improvements.jsonl and current scores
  IMPROVEMENTS="$SKILL_DIR/improvements.jsonl"

  # Get current score — write to temp file to avoid quoting issues
  RESULT_FILE=$(mktemp)
  "$SCRIPT_DIR/test-runner.sh" "$SKILL_DIR" > "$RESULT_FILE" 2>/dev/null || echo '{"score":0}' > "$RESULT_FILE"

  python3 -c "
import json, datetime, os, sys

skill_name = '$SKILL_NAME'
skill_dir = '$SKILL_DIR'
improvements_path = '$IMPROVEMENTS'
with open('$RESULT_FILE') as rf:
    current_result = json.load(rf)

# Load improvements history
improvements = []
if os.path.exists(improvements_path) and os.path.getsize(improvements_path) > 0:
    with open(improvements_path) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    improvements.append(json.loads(line))
                except json.JSONDecodeError:
                    pass

# Compute stats
total = len(improvements)
kept = sum(1 for i in improvements if i.get('result') in ('kept', 'kept_neutral'))
reverted = sum(1 for i in improvements if i.get('result') == 'reverted')
skipped = sum(1 for i in improvements if i.get('result') == 'skipped')

# Category distribution
categories = {}
for i in improvements:
    cat = i.get('category', 'unknown')
    categories[cat] = categories.get(cat, 0) + 1

# Get best score ever achieved
scores = [i.get('score_after', 0) for i in improvements]
best_score = max(scores) if scores else current_result.get('score', 0)

# What worked (kept improvements sorted by delta)
worked = sorted(
    [i for i in improvements if i.get('result') == 'kept' and i.get('delta', 0) > 0],
    key=lambda x: x.get('delta', 0),
    reverse=True
)[:5]

# What didn't work (reverted, for avoiding repeats)
failed = [i for i in improvements if i.get('result') == 'reverted'][-5:]

# Last 2 categories (for rotation)
last_cats = [i.get('category', '') for i in improvements[-2:]]

# Build SKILL_STATE.md
state = f'''---
skill: {skill_name}
current_score: {current_result.get('score', 0)}
best_score: {best_score}
total_iterations: {total}
kept: {kept}
reverted: {reverted}
skipped: {skipped}
last_updated: {datetime.datetime.now().isoformat()}
---

# {skill_name} — Improvement State

Compressed knowledge layer for stateless agent resumption.
Generated by session-state.sh — do not edit manually.

## Current Scores

| Metric | Score |
|--------|-------|
| Composite | {current_result.get('score', 0)} |
| Structure | {current_result.get('structure_score', 0)} |
| Clarity | {current_result.get('clarity_score', 0)} |
| Completeness | {current_result.get('completeness_score', 0)} |

## What Worked

'''

if worked:
    for w in worked:
        state += f\"\"\"- [{w.get('category')}] {w.get('action', '?')} (+{w.get('delta', 0)})
\"\"\"
else:
    state += '- No successful improvements yet.\n'

state += '''
## What Failed (avoid repeating)

'''

if failed:
    for f_item in failed:
        state += f\"\"\"- [{f_item.get('category')}] {f_item.get('action', '?')} ({f_item.get('delta', 0)})
\"\"\"
else:
    state += '- No failed attempts yet.\n'

state += f'''
## Category Distribution

'''

for cat, count in sorted(categories.items(), key=lambda x: x[1], reverse=True):
    state += f'- {cat}: {count} iterations\n'

if not categories:
    state += '- No iterations yet.\n'

state += f'''
## Resume Context

- Last 2 categories: {', '.join(last_cats) if last_cats else 'none'}
- Keep rate: {round(kept/total*100, 1) if total > 0 else 0}%
- Weakest dimension: {'clarity' if current_result.get('clarity_score', 100) <= current_result.get('structure_score', 100) and current_result.get('clarity_score', 100) <= current_result.get('completeness_score', 100) else ('completeness' if current_result.get('completeness_score', 100) <= current_result.get('structure_score', 100) else 'structure')}
- Suggested next focus: improve the weakest dimension first
'''

with open(f'{skill_dir}/SKILL_STATE.md', 'w') as out:
    out.write(state)

print(f'SKILL_STATE.md written for {skill_name} (score: {current_result.get(\"score\", 0)}, {total} iterations)')
"
  rm -f "$RESULT_FILE"
  ;;

summary)
  # One-line summary for quick context loading
  if [ ! -f "$SKILL_DIR/SKILL_STATE.md" ]; then
    # Generate from test runner
    RESULT=$("$SCRIPT_DIR/test-runner.sh" "$SKILL_DIR" 2>/dev/null || echo '{"score":0}')
    SCORE=$(echo "$RESULT" | python3 -c "import sys,json; print(json.load(sys.stdin).get('score', 0))" 2>/dev/null || echo "0")
    echo "$SKILL_NAME: score=$SCORE (no improvement history)"
  else
    python3 -c "
with open('$SKILL_DIR/SKILL_STATE.md') as f:
    content = f.read()
parts = content.split('---')
if len(parts) >= 3:
    fm = {}
    for line in parts[1].strip().split('\n'):
        if ':' in line:
            key, val = line.split(':', 1)
            fm[key.strip()] = val.strip()
    print(f\"$SKILL_NAME: score={fm.get('current_score','?')} best={fm.get('best_score','?')} iterations={fm.get('total_iterations','0')} kept={fm.get('kept','0')}\")
else:
    print('$SKILL_NAME: unparseable state')
"
  fi
  ;;

*)
  echo "Unknown action: $ACTION. Use read, write, or summary." >&2
  exit 2
  ;;
esac
