import type { IntegrationId, IntegrationMeta } from '@repo/types';

// ---------------------------------------------------------------------------
// Static integration registry — all supported integrations and their metadata.
// Status is resolved at runtime by the /api/integrations/status endpoint.
// integration_type: native (first-party), mcp (via MCP server), coming_soon
// ---------------------------------------------------------------------------

export const INTEGRATIONS: IntegrationMeta[] = [
  // ── Source Control ──
  {
    id: 'github',
    name: 'GitHub',
    description: 'Source control, pull requests, code review, and CI/CD.',
    category: 'source_control',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://github.com',
    healthCheckUrl: 'https://www.githubstatus.com/api/v2/status.json',
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    description: 'Git repositories, CI/CD pipelines, and merge requests.',
    category: 'source_control',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://gitlab.com',
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    description: 'Atlassian-hosted Git repos and pipelines.',
    category: 'source_control',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://bitbucket.org',
  },

  // ── AI Providers ──
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude models for AI agents and chat.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://anthropic.com',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT models and transcription.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://openai.com',
  },
  {
    id: 'google_gemini',
    name: 'Google Gemini',
    description: 'Gemini models for AI agents.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://ai.google.dev',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    description: 'Mistral models for AI agents.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://mistral.ai',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Fast LLM inference.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://groq.com',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'Text-to-speech and voice cloning.',
    category: 'ai_provider',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://elevenlabs.io',
  },

  // ── Project Management ──
  {
    id: 'linear',
    name: 'Linear',
    description: 'Issue tracking and project management for engineering teams.',
    category: 'project_management',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://linear.app',
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Enterprise project management and issue tracking.',
    category: 'project_management',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://atlassian.com/jira',
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Work management and task collaboration.',
    category: 'project_management',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://asana.com',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Docs, wikis, and knowledge base for teams.',
    category: 'project_management',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://notion.so',
  },

  // ── Communication ──
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team notifications and slash commands.',
    category: 'communication',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://slack.com',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Notifications in your Discord server.',
    category: 'communication',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://discord.com',
  },
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    description: 'Notifications in Teams channels.',
    category: 'communication',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://teams.microsoft.com',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Notifications via Telegram bot.',
    category: 'communication',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://telegram.org',
  },
  {
    id: 'sms_telecom',
    name: 'SMS / Telecom',
    description: 'Text message alerts.',
    category: 'communication',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: '',
  },

  // ── Databases ──
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Database, auth, and real-time subscriptions.',
    category: 'databases',
    scope: 'platform',
    integration_type: 'native',
    url: 'https://supabase.com',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    description: 'Direct PostgreSQL database access for agents.',
    category: 'databases',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://postgresql.org',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    description: 'NoSQL document database.',
    category: 'databases',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://mongodb.com',
  },
  {
    id: 'redis',
    name: 'Redis',
    description: 'In-memory data store, cache, and pub/sub.',
    category: 'databases',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://redis.io',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    description: 'Relational database management system.',
    category: 'databases',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://mysql.com',
  },
  {
    id: 'neon',
    name: 'Neon',
    description: 'Serverless PostgreSQL with branching.',
    category: 'databases',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://neon.tech',
  },

  // ── Deployment ──
  {
    id: 'railway',
    name: 'Railway',
    description: 'Hosting, deployments, and infrastructure.',
    category: 'deployment',
    scope: 'platform',
    integration_type: 'native',
    url: 'https://railway.com',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    description: 'Web hosting and continuous deployment.',
    category: 'deployment',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://netlify.com',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    description: 'CDN, Workers, DNS, and security.',
    category: 'deployment',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://cloudflare.com',
  },

  // ── Monitoring ──
  {
    id: 'sentry',
    name: 'Sentry',
    description: 'Error tracking and performance monitoring.',
    category: 'monitoring',
    scope: 'platform',
    integration_type: 'native',
    url: 'https://sentry.io',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    description: 'APM, logs, and infrastructure monitoring.',
    category: 'monitoring',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://datadoghq.com',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    description: 'Incident management and on-call scheduling.',
    category: 'monitoring',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://pagerduty.com',
  },

  // ── Cloud Platforms ──
  {
    id: 'aws',
    name: 'AWS',
    description: 'Amazon Web Services infrastructure and deployment.',
    category: 'cloud',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://aws.amazon.com',
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    description: 'Google Cloud Platform services.',
    category: 'cloud',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://cloud.google.com',
  },
  {
    id: 'azure',
    name: 'Microsoft Azure',
    description: 'Microsoft cloud services and deployment.',
    category: 'cloud',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://azure.microsoft.com',
  },

  // ── Research & Web Data ──
  {
    id: 'tavily',
    name: 'Tavily',
    description: 'AI-optimized search API for web research.',
    category: 'research',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://tavily.com',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    description: 'Web scraping and crawling for structured data extraction.',
    category: 'research',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://firecrawl.dev',
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    description: 'Google AI-powered research and note-taking.',
    category: 'research',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://notebooklm.google.com',
  },

  // ── Design ──
  {
    id: 'figma',
    name: 'Figma',
    description: 'UI design, prototyping, and design-to-code.',
    category: 'design',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://figma.com',
  },

  // ── Documentation ──
  {
    id: 'confluence',
    name: 'Confluence',
    description: 'Enterprise wikis and documentation.',
    category: 'documentation',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://atlassian.com/confluence',
  },

  // ── Email ──
  {
    id: 'agentmail',
    name: 'AgentMail',
    description: 'AI agent email inboxes and messaging.',
    category: 'email',
    scope: 'platform',
    integration_type: 'native',
    url: 'https://agentmail.to',
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Transactional email API for developers.',
    category: 'email',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://resend.com',
  },
  {
    id: 'twilio',
    name: 'Twilio',
    description: 'SMS, voice, and email delivery APIs.',
    category: 'email',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://twilio.com',
  },

  // ── Billing ──
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Payment processing and subscriptions.',
    category: 'billing',
    scope: 'platform',
    integration_type: 'native',
    url: 'https://stripe.com',
  },

  // ── Automation ──
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect to 7,000+ apps with automated workflows.',
    category: 'automation',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://zapier.com',
  },
  {
    id: 'make_com',
    name: 'Make',
    description: 'Visual workflow automation platform.',
    category: 'automation',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://make.com',
  },

  // ── Commerce ──
  {
    id: 'shopify',
    name: 'Shopify',
    description: 'E-commerce platform and storefront.',
    category: 'commerce',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://shopify.com',
  },

  // ── CRM ──
  {
    id: 'hubspot',
    name: 'HubSpot',
    description: 'CRM, marketing, and sales platform.',
    category: 'crm',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://hubspot.com',
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    description: 'Enterprise CRM and customer platform.',
    category: 'crm',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://salesforce.com',
  },

  // ── Data & Analytics ──
  {
    id: 'snowflake',
    name: 'Snowflake',
    description: 'Cloud data warehouse and analytics.',
    category: 'data_analytics',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://snowflake.com',
  },
  {
    id: 'bigquery',
    name: 'BigQuery',
    description: 'Google serverless data warehouse.',
    category: 'data_analytics',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://cloud.google.com/bigquery',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Spreadsheet-database hybrid for structured data.',
    category: 'data_analytics',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://airtable.com',
  },
  {
    id: 'google_analytics',
    name: 'Google Analytics',
    description: 'Web analytics and traffic insights.',
    category: 'data_analytics',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://analytics.google.com',
  },

  // ── Testing ──
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Browser automation and end-to-end testing.',
    category: 'testing',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://playwright.dev',
  },

  // ── DevOps ──
  {
    id: 'docker',
    name: 'Docker',
    description: 'Container building and management.',
    category: 'devops',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://docker.com',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    description: 'Container orchestration and deployment.',
    category: 'devops',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://kubernetes.io',
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    description: 'Continuous integration and delivery.',
    category: 'devops',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://circleci.com',
  },
  {
    id: 'github_actions',
    name: 'GitHub Actions',
    description: 'CI/CD workflows and automation.',
    category: 'devops',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://github.com/features/actions',
  },
  {
    id: 'launchdarkly',
    name: 'LaunchDarkly',
    description: 'Feature flags and progressive delivery.',
    category: 'devops',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://launchdarkly.com',
  },

  // ── Scheduling ──
  {
    id: 'calendly',
    name: 'Calendly',
    description: 'Meeting scheduling and calendar management.',
    category: 'scheduling',
    scope: 'workspace',
    integration_type: 'coming_soon',
    url: 'https://calendly.com',
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    description: 'Calendar management and event scheduling.',
    category: 'scheduling',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://calendar.google.com',
  },

  // ── Storage & Productivity ──
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    description: 'Gmail, Drive, Sheets, and Docs.',
    category: 'storage',
    scope: 'workspace',
    integration_type: 'mcp',
    url: 'https://workspace.google.com',
  },

  // ── IDE & CLI ──
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-native code editor with MCP support.',
    category: 'ide',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://cursor.com',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    description: 'AI-powered IDE by Codeium.',
    category: 'ide',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://codeium.com/windsurf',
  },
  {
    id: 'claude_code',
    name: 'Claude Code',
    description: 'Anthropic CLI for agentic coding.',
    category: 'ide',
    scope: 'workspace',
    integration_type: 'native',
    url: 'https://claude.ai',
  },
];

/** Category display labels and ordering */
export const CATEGORY_LABELS: Record<string, string> = {
  source_control: 'Source Control',
  ai_provider: 'AI Providers',
  project_management: 'Project Management',
  communication: 'Communication',
  databases: 'Databases',
  deployment: 'Deployment',
  monitoring: 'Monitoring',
  cloud: 'Cloud Platforms',
  research: 'Research & Web Data',
  design: 'Design',
  documentation: 'Documentation',
  email: 'Email',
  billing: 'Billing',
  automation: 'Automation',
  commerce: 'Commerce',
  crm: 'CRM',
  data_analytics: 'Data & Analytics',
  testing: 'Testing',
  devops: 'DevOps & CI/CD',
  scheduling: 'Scheduling',
  storage: 'Storage & Productivity',
  ide: 'IDE & CLI',
};

/** Category display order */
export const CATEGORY_ORDER = [
  'source_control',
  'ai_provider',
  'project_management',
  'communication',
  'databases',
  'deployment',
  'monitoring',
  'cloud',
  'research',
  'design',
  'documentation',
  'email',
  'billing',
  'automation',
  'commerce',
  'crm',
  'data_analytics',
  'testing',
  'devops',
  'scheduling',
  'storage',
  'ide',
] as const;

/**
 * Get the logo path for an integration.
 * Color logos stored in /public/integrations/{id}.svg or .png
 * Falls back to null if no logo file exists.
 */
export function getIntegrationLogoPath(id: IntegrationId): string | null {
  // PNGs (vendor-provided logomarks)
  const pngLogos: Set<string> = new Set([
    'tavily',
    'firecrawl',
    'make_com',
    'notebooklm',
    'agentmail',
  ]);
  if (pngLogos.has(id)) return `/integrations/${id}.png`;

  // SVGs (SimpleIcons or custom)
  const hasLogo: Set<string> = new Set([
    'github',
    'gitlab',
    'anthropic',
    'openai',
    'stripe',
    'sentry',
    'railway',
    'supabase',
    'figma',
    'notion',
    'linear',
    'jira',
    'postgresql',
    'mongodb',
    'redis',
    'mysql',
    'neon',
    'docker',
    'netlify',
    'cloudflare',
    'datadog',
    'pagerduty',
    'aws',
    'gcp',
    'azure',
    'discord',
    'microsoft_teams',
    'telegram',
    'google_gemini',
    'mistral',
    'groq',
    'elevenlabs',
    'slack',
    'playwright',
    'resend',
    'zapier',
    'shopify',
    'hubspot',
    'salesforce',
    'snowflake',
    'bigquery',
    'airtable',
    'google_analytics',
    'google_calendar',
    'google_workspace',
    'calendly',
    'launchdarkly',
    'circleci',
    'kubernetes',
    'github_actions',
    'confluence',
    'asana',
    'bitbucket',
    'twilio',
  ]);
  return hasLogo.has(id) ? `/integrations/${id}.svg` : null;
}
